theme = "slick"


[icons]
name = "awesome"
[icons.overrides]
backlight_empty = "  "
backlight_partial1 = "  "
backlight_partial2 = "  "
backlight_partial3 = "  "
backlight_full = "  "


[[block]]
block = "music"
buttons = ["prev", "play", "next"]

[[block]]
block = "disk_space"
path = "/"
alias = "Root"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

# [[block]]
# block = "disk_space"
# path = "/mnt/"
# alias = "Home"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0
#
# [[block]]
# block = "disk_space"
# path = "/var/"
# alias = "Var"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 10.0
# alert = 5.0

[[block]]
block = "memory"
format_mem = "{Mum} MB / {MTm} MB → {Mup}%"
format_swap = "{SUm} MB / {STm} MB → {SUp}%"
display_type = "memory"
icons = true
clickable = true
interval = 1
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "temperature"
collapsed = false
interval = 1
# format = "{min}° min, {max}° max, {average}° avg"
format = "{average}°C"

[[block]]
block = "cpu"
interval = 1
frequency = true

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

[[block]]
block = "net"
device = "enp2s0"
ip = false
# speed_up = false
# graph_up = true
interval = 1

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = false
# speed_up = false
# graph_up = true
interval = 1

# [[block]]
# block = "networkmanager"


[[block]]
block = "backlight"
# device = "intel_backlight"

[[block]]
block = "sound"
step_width = 1

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

[[block]]
block = "time"
interval = 60
format = "%d/%m/%Y %R"
# format = "%a %d/%m/%Y %R"
