array_width = 100
attr_fn_like_width = 100
binop_separator = "Front"
blank_lines_lower_bound = 0 # Unstable
blank_lines_upper_bound = 1 # Unstable
brace_style = "SameLineWhere" # Unstable
chain_width = 70
combine_control_expr = true # Unstable
comment_width = 100 # Unstable
condense_wildcard_suffixes = true # Unstable
edition = "2018"
empty_item_single_line = true # Unstable
enum_discrim_align_threshold = 0 # Unstable
error_on_line_overflow = false # Unstable
error_on_unformatted = false # Unstable
fn_params_layout = "Compressed"
fn_call_width = 80
fn_single_line = false # Unstable
force_explicit_abi = true
force_multiline_blocks = false # Unstable
format_code_in_doc_comments = true # Unstable
format_macro_matchers = false # Unstable
format_macro_bodies = true # Unstable
format_strings = true # Unstable
hard_tabs = false
hide_parse_errors = false # Unstable
ignore = []
imports_indent = "Block" # Unstable
imports_layout = "Mixed" # Unstable
indent_style = "Block" # Unstable
inline_attribute_width = 0 # Unstable
license_template_path = "" # Unstable
match_arm_blocks = true # Unstable
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
max_width = 100
merge_derives = true
merge_imports = true # Unstable
newline_style = "Auto"
normalize_comments = true # Unstable
normalize_doc_attributes = true # Unstable
overflow_delimited_expr = false # Unstable
remove_nested_parens = true
reorder_impl_items = true # Unstable
reorder_imports = true
reorder_modules = true
# required_version = ""
single_line_if_else_max_width = 60
space_after_colon = true # Unstable
space_before_colon = false # Unstable
spaces_around_ranges = false # Unstable
space_around_attr_eq = true # Unstable
struct_field_align_threshold = 0 # Unstable
struct_lit_single_line = true # Unstable
struct_lit_width = 20
struct_variant_width = 40
tab_spaces = 4
trailing_comma = "Vertical" # Unstable
trailing_semicolon = true # Unstable
type_punctuation_density = "Wide" # Unstable
unstable_features = true
use_field_init_shorthand = true
width_heuristics = "Scaled"
use_try_shorthand = true
where_single_line = false # Unstable
wrap_comments = true # Unstable

