language: generic # default to ruby
sudo: required

services:
    - docker

script:
    - docker run -v $(pwd):/root/.config/nvim autozimu/languageclientneovim bash -c "export PATH=$PATH:~/.cargo/bin && cd /root/.config/nvim/rplugin/python3 && make"
