-- {{{ Global Variable Definitions }}}

modkey       = "Mod4"
altkey       = "Mod1"
terminal     = "alacritty"
editor       = os.getenv("EDITOR") or "nvim"
gui_editor   = "atom"
gui_editor2  = "code"
browser      = "firefox" -- "firefox-developer-edition"
scrlocker    = "~/.config/awesome/i3lock-fancy/lock"
filemanager  = "dolphin"
filemanager2 = "alacritty -e ranger"
screenshot   = "flameshot gui"
rofi         = "/usr/bin/rofi -show run -sidebar-mode"
python       = "alacritty -e python"
julia        = "alacritty -e julia"
